# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins: 
- jekyll-paginate
- jekyll-gist

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hrishikesh P
tagline:          'Game Developer'
description:      'Student Game Developer'
url:              http://hyde.getpoole.com
baseurl:          /


author:
  name:           'Hrishikesh P'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hrishikeshpramod/hrishikeshpramod.github.io

